version: '2.0'

services:
  master:
    image: 'dylanguedes/commited_spark'
    command: /scripts/spark_master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      EXPERIMENT_SCENARIO: CITY_SCALE
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 9999:9999
    volumes:
      - ./data:/tmp/data
      - ./scripts:/scripts
      - ./dependencies:/dependencies
    container_name: 'master'

  worker:
    container_name: 'worker'
    image: 'dylanguedes/commited_spark'
    command: /scripts/spark_worker
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data:/tmp/data
      - ./scripts:/scripts
      - ./dependencies:/dependencies


  kafka:
    container_name: kafka
    image: 'spotify/kafka'
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      ADVERTISED_HOST: 172.17.0.1


  hadoop:
    container_name: "hadoop"
    image: "dylanguedes/hadoop_model"
    ports:
      - "8020:8020"
      - "50070:50070"
      - "50010:50010"
      - "9000:9000"

networks:
  default:
    external:
      name: platform
